import '@/styles/globals.css'
import NavLayout from '@/components/Layouts/NavLayout'
import Head from 'next/head'
export default function App({ Component, pageProps }) {
  return <>
  <Head >
      <title>Stone World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/senku.svg" />
      </Head>
      <NavLayout><Component {...pageProps} /></NavLayout></>
}
