import Layout from "@/components/layout/layout";
import '@/styles/globals.css'
import Head from "next/head";
import { Fragment } from "react";
export default function App({ Component, pageProps }) {
  return (
    <><Head>
    <title>New Next Js App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/mpho.svg" />
  </Head>
    <Fragment>
  <Layout>
    <Component {...pageProps}/>
    </Layout>
   </Fragment></>)
}
