import FeaturedPosts from '@/componets/Home-Page/FeaturedPosts';
import Hero from '@/componets/Home-Page/Hero';
import Head from 'next/head'
import { Fragment } from 'react'
import { getFeaturedPosts } from '@/lib/posts-utils';


const Home=({posts})=> {
  return (
    <>
      <Head>
        <title>Welcome To NextJs Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <main className={``}>
          <Hero/>
          <FeaturedPosts posts={posts}/>
        </main>
      </Fragment>
    </>
  )
}
export const getStaticProps = async () =>{
const fetured = getFeaturedPosts();
return {
  props:{
    posts: fetured
  },
  revalidate: 60
}
}
export default Home;
